# Generated by Django 5.2.3 on 2025-06-15 14:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0002_alter_state_geom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="taluka",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
