# Generated by Django 5.2.3 on 2025-06-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0003_alter_district_geom_alter_taluka_geom"),
    ]

    operations = [
        migrations.AddField(
            model_name="village",
            name="pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="village",
            name="population",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
